//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalProblem
    {
        public int TechnicalProblemID { get; set; }
        public string ProblemDescription { get; set; }
        public int TimetableID { get; set; }
        public bool ProblemStatus { get; set; }
    
        public virtual Timetable Timetable { get; set; }
    }
}
