//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabAuto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timetable()
        {
            this.Attendances = new HashSet<Attendance>();
            this.TechnicalProblems = new HashSet<TechnicalProblem>();
        }
    
        public int TimetableID { get; set; }
        public int TeacherID { get; set; }
        public int CourseID { get; set; }
        public int LabID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Starttime { get; set; }
        public System.TimeSpan Finishtime { get; set; }
        public bool TimetableStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Course Course { get; set; }
        public virtual Lab Lab { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnicalProblem> TechnicalProblems { get; set; }
    }
}
